DEFAULT_FONT = ('Arial', 18)

LOG_DIRNAME = "logs"

WORLD_DIRNAME = "worlds"
STRUCT_DIRNAME  = "structs"
INSTANCES_DIRNAME = "instances"

USERCODE_DIRNAME = "usercode"
USERCODE_TYPES_DIRNAME = "types"
USERCODE_GENERATORS_DIRNAME = "generators"
USERCODE_COMMON_DIRNAME = "common"
USERCODE_SUBDIRS = [USERCODE_TYPES_DIRNAME, USERCODE_GENERATORS_DIRNAME, USERCODE_COMMON_DIRNAME]

INNER_PADDING = 2
OUTER_PADDING = 12
